service: triplan-cms
frameworkVersion: "3"

provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: eu-central-1
  deploymentBucket: triplan-cms-deployment-bucket
  timeout: 20
  environment:
    ["REGION"]: "self:provider.region"
    ["DEFAULT_EXTENSION"]: "png"
    ["CMS_STORAGE_BUCKET_NAME"]: "triplan-cms-bucket"
    ["CMS_STORAGE_BUCKET_DIRECTORY_IMG"]: "img"
    ["CMS_STORAGE_BUCKET_URL"]: "https://triplan-cms-bucket.s3.eu-central-1.amazonaws.com"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucketVersions"
          Resource:
            - "arn:aws:s3:::${self:provider.environment.CMS_STORAGE_BUCKET_NAME}"
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:GetObjectVersion"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::${self:provider.environment.CMS_STORAGE_BUCKET_NAME}/*"

functions:
  restore:
    handler: handler.restore
    events:
      - httpApi:
          path: /restore
          method: post
  upload:
    handler: handler.upload
    events:
      - httpApi:
          path: /upload
          method: post
  find:
    handler: handler.find
    events:
      - httpApi:
          path: /
          method: get

